// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdchaikfuwpdydjbczcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkY2hhaWtmdXdwZHlkamJjemNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjA0MDYsImV4cCI6MjA2OTQzNjQwNn0.d-1yzIXBh-RFBbyxGf5b4goLcD_83sh9SoW1DW2tB3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});